name: Build default outputs

on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
      - 'tools/**'
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: 'global.json'
    - name: Generate OpenAPI
      run: dotnet run --project tools/EVA.SDK.Generator.V2/ -- generate openapi -i spec/spec.json -o output/openapi --overwrite --assembly EVA.Core --remove inheritance empty-types nested-types
    - name: Generate ApiDocs
      run: dotnet run --project tools/EVA.SDK.Generator.V2/ -- generate apidocs -i spec/spec.json -o output/apidocs --overwrite
    - name: Commit changes
      run: 'git add .;git config --global user.email "ruben.oost@newblack.io";git config --global user.name "Ruben Oost";git diff-index --quiet HEAD || git commit -m "Outputs for: ${{ github.event.head_commit.message }}";git push origin main'
    - name: Upload ApiDocs
      run: |
        curl -H "X-TYPESENSE-API-KEY: ${{ secrets.TYPESENSE_DEVELOP_KEY }}" -X POST -T typesense.ndjson "https://${{ secrets.TYPESENSE_DEVELOP_CLUSTER }}/collections/${{ secrets.TYPESENSE_DEVELOP_COLLECTION }}/documents/import?action=upsert"