name: Build default outputs

on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
      - 'tools/**'
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: 'global.json'
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
    - name: Generate OpenAPI
      run: dotnet run --project tools/EVA.SDK.Generator.V2/ -- generate openapi -i spec/spec.json -o output/openapi --overwrite --opt-terse --opt-format json
    - name: Upload OpenAPI
      uses: alphadoc-io/action-update-api@v1
      with:
        OPENAPI_FILE: output/openapi/openapi.json
        ORGANISATION: "newblack"
        PROJECT_ID: "${{ secrets.AD_PROJECT }}"
        DOCUMENT_ID: "${{ secrets.AD_DOCUMENT_BEYOND }}"
        USERNAME: "${{ secrets.AD_USERNAME }}"
        PASSWORD: "${{ secrets.AD_PASSWORD }}"
    - name: Generate ApiDocs
      run: dotnet run --project tools/EVA.SDK.Generator.V2/ -- generate apidocs -i spec/spec.json -o output/apidocs --overwrite
    - name: Commit changes
      run: 'git add .;git config --global user.email "ruben.oost@newblack.io";git config --global user.name "Ruben Oost";git diff-index --quiet HEAD || git commit -m "Outputs for: ${{ github.event.head_commit.message }}";git push origin main'