name: Build default outputs

on:
  push:
    branches:
      - main
    paths:
      - 'spec/**'
      - 'tools/**'
  workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      AWS_PAGER: ''
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: 'global.json'
    - name: Generate OpenAPI
      run: dotnet run --project tools/EVA.SDK.Generator.V2/ -- generate openapi -i spec/spec.json -o output/openapi --overwrite --opt-terse --opt-format json --opt-examples-folder "examples/" --assembly "-EVA.Global" "-EVA.ShelfManagement" "-EVA.Workforce" "-EVA.Sync"
    - name: Commit changes
      run: 'git add .;git config --global user.email "ruben.oost@newblack.io";git config --global user.name "Ruben Oost";git diff-index --quiet HEAD || git commit -m "Outputs for: ${{ github.event.head_commit.message }}";git push origin main'

    - name: Upload OpenAPI and get versionId
      shell: bash
      run: |
        echo "{\"apiSpec\": \"$(base64 -w 0 ./output/openapi/openapi.json)\",\"apiSpecType\": \"application/json\"}" > body.json
        version_id=$(curl -f -s -X POST \
          -H "X-API-KEY: ${{ secrets.ALPHADOC_APIKEY }}" \
          -H "Content-Type: application/json" \
          --data-binary "@./body.json" \
          "https://newblack.alphadoc.io/v1/projectVersions/${{ secrets.PROJECT_VERSION_ID }}/apiSpecs/${{ secrets.AD_DOCUMENT_BEYOND }}/versions" | jq -r '.id')
        echo "versionId=$version_id" >> $GITHUB_ENV

    - name: Set API specification as default
      shell: bash
      run: |
        curl -f -s -X PUT \
          -H "X-API-KEY: ${{ secrets.ALPHADOC_APIKEY }}" \
          -H "Content-Type: application/json" \
          "https://newblack.alphadoc.io/v1/projectVersions/${{ secrets.PROJECT_VERSION_ID }}/apiSpecs/${{ secrets.API_SPEC_ID }}/versions/${{ env.versionId }}"

    - name: Publish document
      shell: bash
      run: |
        curl -f -s -X POST \
          -H "X-API-KEY: ${{ secrets.ALPHADOC_APIKEY }}" \
          -H "Content-Type: application/json" \
          "https://newblack.alphadoc.io/v1/projectVersions/${{ secrets.PROJECT_VERSION_ID }}/publish"
